export const tableData = [
  { id: 1, nombre: "Ana García", departamento: "Ingeniería", cargo: "Dev Frontend", salario: 42000, activo: "Sí" },
  { id: 2, nombre: "Carlos López", departamento: "Diseño", cargo: "UI/UX Designer", salario: 38000, activo: "Sí" },
  { id: 3, nombre: "Marta Sánchez", departamento: "Producto", cargo: "Product Manager", salario: 55000, activo: "No" },
  { id: 4, nombre: "David Martínez", departamento: "Ingeniería", cargo: "Dev Backend", salario: 46000, activo: "Sí" },
  { id: 5, nombre: "Lucía Fernández", departamento: "RRHH", cargo: "HR Specialist", salario: 34000, activo: "Sí" },
  { id: 6, nombre: "Pablo Ruiz", departamento: "Ingeniería", cargo: "DevOps", salario: 50000, activo: "Sí" },
  { id: 7, nombre: "Sara Torres", departamento: "Marketing", cargo: "SEO Analyst", salario: 31000, activo: "No" },
  { id: 8, nombre: "Javier Moreno", departamento: "Ventas", cargo: "Sales Lead", salario: 44000, activo: "Sí" },
  { id: 9, nombre: "Elena Jiménez", departamento: "Ingeniería", cargo: "QA Engineer", salario: 39000, activo: "Sí" },
  { id: 10, nombre: "Raúl Díaz", departamento: "Finanzas", cargo: "Controller", salario: 52000, activo: "Sí" },
  { id: 11, nombre: "Isabel Romero", departamento: "Diseño", cargo: "Motion Designer", salario: 36000, activo: "No" },
  { id: 12, nombre: "Miguel Álvarez", departamento: "Producto", cargo: "Scrum Master", salario: 49000, activo: "Sí" },
  { id: 13, nombre: "Nuria Vega", departamento: "Marketing", cargo: "Content Manager", salario: 33000, activo: "Sí" },
  { id: 14, nombre: "Tomás Castillo", departamento: "Ingeniería", cargo: "Tech Lead", salario: 62000, activo: "Sí" },
  { id: 15, nombre: "Beatriz Molina", departamento: "RRHH", cargo: "Talent Recruiter", salario: 35000, activo: "No" },
  { id: 16, nombre: "English Baird", departamento: "Marketing", cargo: "QA Engineer", salario: 40, activo: "si" },
  { id: 17, nombre: "Cabrera Goodman", departamento: "Finanzas", cargo: "Sales Lead", salario: 25, activo: "si" },
  { id: 18, nombre: "Lowe Hopkins", departamento: "Marketing", cargo: "Dev Frontend", salario: 24, activo: "si" },
  { id: 19, nombre: "Martin Golden", departamento: "Marketing", cargo: "HR Specialist", salario: 20, activo: "si" },
  { id: 20, nombre: "Sheena Roberson", departamento: "Ingenieria", cargo: "Product Manager", salario: 28, activo: "no" },
  { id: 21, nombre: "Annette Rogers", departamento: "Ventas", cargo: "DevOps", salario: 29, activo: "si" },
  { id: 22, nombre: "Viola Fernandez", departamento: "Ventas", cargo: "Sales Lead", salario: 40, activo: "no" },
  { id: 23, nombre: "Payne Mack", departamento: "Ventas", cargo: "HR Specialist", salario: 31, activo: "si" },
  { id: 24, nombre: "Lucinda Farmer", departamento: "Marketing", cargo: "Sales Lead", salario: 38, activo: "no" },
  { id: 25, nombre: "Hyde Guzman", departamento: "Producto", cargo: "QA Engineer", salario: 22, activo: "no" },
  { id: 26, nombre: "Johns Burt", departamento: "Producto", cargo: "Product Manager", salario: 28, activo: "si" },
  { id: 27, nombre: "Iris Huffman", departamento: "Ventas", cargo: "SEO Analyst", salario: 32, activo: "no" },
  { id: 28, nombre: "Teresa Pope", departamento: "Ventas", cargo: "Product Manager", salario: 39, activo: "si" },
  { id: 29, nombre: "Ortega Mendez", departamento: "Ventas", cargo: "HR Specialist", salario: 32, activo: "si" },
  { id: 30, nombre: "Wiley Higgins", departamento: "Finanzas", cargo: "QA Engineer", salario: 38, activo: "si" },
  { id: 31, nombre: "Atkins Gutierrez", departamento: "Producto", cargo: "Dev Frontend", salario: 22, activo: "no" },
  { id: 32, nombre: "Sheryl Mendoza", departamento: "Ventas", cargo: "UX/UI Design", salario: 29, activo: "no" },
  { id: 33, nombre: "Peters Jordan", departamento: "Ventas", cargo: "QA Engineer", salario: 29, activo: "si" },
  { id: 34, nombre: "Ronda Brady", departamento: "Diseño", cargo: "DevOps", salario: 39, activo: "no" },
  { id: 35, nombre: "Deloris Wolfe", departamento: "Ventas", cargo: "Product Manager", salario: 31, activo: "no" },
  { id: 36, nombre: "Debbie Gross", departamento: "Finanzas", cargo: "Dev Frontend", salario: 20, activo: "no" },
  { id: 37, nombre: "Caitlin Watts", departamento: "Finanzas", cargo: "UX/UI Design", salario: 35, activo: "si" },
  { id: 38, nombre: "Morgan Jennings", departamento: "Diseño", cargo: "Dev Backend", salario: 31, activo: "no" },
  { id: 39, nombre: "Griffin Rocha", departamento: "Ventas", cargo: "Dev Backend", salario: 20, activo: "no" },
  { id: 40, nombre: "Goodwin Levy", departamento: "Marketing", cargo: "DevOps", salario: 39, activo: "no" },
  { id: 41, nombre: "Richardson Mcknight", departamento: "Producto", cargo: "Dev Frontend", salario: 22, activo: "no" },
  { id: 42, nombre: "Langley Myers", departamento: "Finanzas", cargo: "SEO Analyst", salario: 37, activo: "no" },
  { id: 43, nombre: "Barker Curtis", departamento: "Diseño", cargo: "Dev Backend", salario: 34, activo: "no" },
  { id: 44, nombre: "Chen Payne", departamento: "Marketing", cargo: "Dev Backend", salario: 37, activo: "no" },
  { id: 45, nombre: "Jane Mckay", departamento: "Ingenieria", cargo: "Product Manager", salario: 23, activo: "si" },
  { id: 46, nombre: "Dixon Guerra", departamento: "Marketing", cargo: "QA Engineer", salario: 29, activo: "no" },
  { id: 47, nombre: "Marylou Carter", departamento: "Marketing", cargo: "Dev Backend", salario: 27, activo: "si" },
  { id: 48, nombre: "Crystal Gilmore", departamento: "Producto", cargo: "UX/UI Design", salario: 40, activo: "si" },
  { id: 49, nombre: "Meagan Atkins", departamento: "Producto", cargo: "HR Specialist", salario: 30, activo: "no" },
  { id: 50, nombre: "Le Duffy", departamento: "Producto", cargo: "HR Specialist", salario: 33, activo: "si" },
  { id: 51, nombre: "Jodie Curry", departamento: "RRHH", cargo: "Dev Frontend", salario: 27, activo: "si" },
  { id: 52, nombre: "Dee Martin", departamento: "Diseño", cargo: "Sales Lead", salario: 38, activo: "si" },
  { id: 53, nombre: "Dionne Parks", departamento: "Producto", cargo: "Dev Frontend", salario: 34, activo: "no" },
  { id: 54, nombre: "Graves Gould", departamento: "Ventas", cargo: "Dev Frontend", salario: 39, activo: "no" },
  { id: 55, nombre: "Josefina Ross", departamento: "Marketing", cargo: "UX/UI Design", salario: 37, activo: "si" },
  { id: 56, nombre: "Stanton Murray", departamento: "RRHH", cargo: "Sales Lead", salario: 40, activo: "no" },
  { id: 57, nombre: "Rhea Bond", departamento: "Finanzas", cargo: "Sales Lead", salario: 31, activo: "si" },
  { id: 58, nombre: "Sharron Meyer", departamento: "Ventas", cargo: "HR Specialist", salario: 40, activo: "si" },
  { id: 59, nombre: "Delia Ware", departamento: "Ingenieria", cargo: "HR Specialist", salario: 40, activo: "si" },
  { id: 60, nombre: "Gutierrez Palmer", departamento: "Producto", cargo: "SEO Analyst", salario: 29, activo: "no" },
  { id: 61, nombre: "Padilla Osborn", departamento: "Diseño", cargo: "UX/UI Design", salario: 39, activo: "no" },
  { id: 62, nombre: "Romero Browning", departamento: "RRHH", cargo: "HR Specialist", salario: 34, activo: "si" },
  { id: 63, nombre: "Glenda Oneill", departamento: "Ventas", cargo: "Dev Backend", salario: 32, activo: "no" },
  { id: 64, nombre: "Bianca Parrish", departamento: "Ingenieria", cargo: "HR Specialist", salario: 26, activo: "si" },
  { id: 65, nombre: "Cunningham Snider", departamento: "Ventas", cargo: "SEO Analyst", salario: 30, activo: "si" }
];